---
deployment:
  tasks:
    - export APPDIR=/home1/yvysduaz/repositories/lets-talk-node
    - cd $APPDIR
    - /bin/rm -rf node_modules dist
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
